### ISSUE TITLE
[bug] logic of UpdatePod should not be called when scale in/out.

### ISSUE THREAD

**Issue by runkecheng** [radondb/radondb-mysql-kubernetes#320]
**Describe the problem**

If only `replicas` changes, StatefulSet does not generate new `Revison` , so the `UpdatedReplicas` has always been 0.

```
status:
  collisionCount: 0
  currentRevision: sample-mysql-55677794
  observedGeneration: 6
  replicas: 0
  updateRevision: sample-mysql-55677794
```

```
func (s *StatefulSetSyncer) updatePod(ctx context.Context) error {
	if s.sfs.Status.UpdatedReplicas >= s.sfs.Status.Replicas {
		return nil
	}
	log.Info("statefulSet was changed, run update")
```

**To Reproduce**

**Expected behavior**

use `currentRevision == updateRevision`

**Environment:**

- RadonDB MySQL version:
