### ISSUE TITLE
[bug] local-storage storageclass, S3 restore has skip.

### ISSUE THREAD

**Issue by acekingke** [radondb/radondb-mysql-kubernetes#327]
**Describe the problem**

if use yaml as follow, S3 backup restore, it will skip the restore process.
```
persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    storageClass: "local-storage"
    size: 20Gi
```
![image](https://user-images.githubusercontent.com/7586502/144813084-05f0b874-2c81-4b56-8b36-a596269d1354.png)

**To Reproduce**

1. the reason is that : updatePvc will delete the pvc, but will not delete data in local-storage, so it will skip the restore process.
2. It will modify the sidecar , when local-storage , should delete the direcotry all. then restore it.
3. local-storage do not support extend pvc. 

**Expected behavior**

**Environment:**
local storage provider 
kubeShpere 3.1.1

- RadonDB MySQL version: v2.1.1
