### ISSUE TITLE
[bug] Pod Label do not support INVALID/IDLE/LEARNER/STOPPED/UNKNOW

### ISSUE THREAD

**Issue by acekingke** [radondb/radondb-mysql-kubernetes#330]
**Describe the problem**

After force kill Xenon container in pod, switch leader multi times, Some Pod raft status is INVALID, but the pod is still follower , and in the follower service list.

**To Reproduce**
 1. Force kill Xenon container in pod, switch leader multi times
 2. at same time , sysbench pressing it

use shell to do this:
sysbench:
use yaml file:
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sysbench
  name: sysbench
spec:
  containers:
  - command:
    - bash 
    - -c 
    - -- 
    args: ["while true; do sleep 30; done;"]
    image: severalnines/sysbench
    name: sysbench
  restartPolicy: Never
```
run the sysbench pod ，in command line 
run shell 

```shell
while true ; do \
sysbench \
    --db-driver=mysql \
    --report-interval=2 \
    --mysql-table-engine=innodb \
    --oltp-table-size=1000000 \
    --oltp-tables-count=64 \
    --threads=16 \
    --time=99999 \
    --mysql-host=sample-leader \
    --mysql-port=3306 \
    --mysql-user=sbtest \
    --mysql-password=password \
    /usr/share/sysbench/tests/include/oltp_legacy/oltp.lua \
    run ;\
done

```
during the sysbench
run shell to kill xenon 
```shell
kubectl exec -it svc/sample-leader -c xenon -- pkill xenon
```

1.

**Expected behavior**

**Environment:**

- RadonDB MySQL version: operator v2.1.1
