### ISSUE TITLE
[feature] Optimize operator availability.

### ISSUE THREAD

**Issue by runkecheng** [radondb/radondb-mysql-kubernetes#415]
**Is your feature request related to a problem? Please describe.**

In k8s, default toleration second of pod is 300s, it means when the worker down, pods in this worker must wait 300s to be re-scheduled to other nodes. 

```
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
```

For Operator, if the worker node down where Operator is located, wait 300s obviously too long, this may cause the cluster status out of control, so we need to adjust the timeout time and improve the usability of Operator.

**Describe the solution you'd like**

- Provide configurable parameter tolerationseconds in values.yaml

**Describe alternatives you've considered**

**Additional context**
