### ISSUE TITLE
[feature] Provide more details of backup in spec->status of backup CRD

### ISSUE THREAD

**Issue by Nrehearsal** [radondb/radondb-mysql-kubernetes#453]
**Is your feature request related to a problem? Please describe.**

stuff for integrate s3 storage client is not planed in the next release of DMP, so we need RadonDB MySQL Operator provide some necessary informations to implement one-step restore function(create a new cluster from a backup).

Existing information:
```
spec:
  clustname: radondb-npbw4y
  historyLimit: 3
  hostname: radondb-npbw4y-mysql-1
  image: radondb/mysql-sidecar:v2.1.2
status:
  completed: true
  conditions:
  - lastTransitionTime: "2022-04-14T07:29:08Z"
    message: ""
    reason: ""
    status: "True"
    type: Complete
```

```restoreFrom``` is missing in Backup CR
```
spec:
  backupSecretName: $S3_SECRET_NAME
  restoreFrom: "backup_20224147294"
```

**Describe the solution you'd like**

Backup detail of PostgreSQL:
```
full backup: 20220415-191402F
            timestamp start/stop: 2022-04-15 19:14:02 +0800 CST / 2022-04-15 19:14:22 +0800 CST
            wal start/stop: 000000010000000000000002 / 000000010000000000000002
            database size: 31.2MiB, backup size: 31.2MiB
            repository size: 3.8MiB, repository backup size: 3.8MiB
            backup reference list:
```

***Our needs***:
- Add cluster name for backup artifact, such as ```radondb-npbw4y_full_backup_20224147294```
- Provide artifact name of backup
- Provide backup type, such as full, incr, diff
- Provide data size

Hope to provide the above information as much as possible

**Describe alternatives you've considered**

**Additional context**
