### ISSUE TITLE
备份到 S3 失败

### ISSUE THREAD

**Issue by zhuyaguang** [radondb/radondb-mysql-kubernetes#646]
secret 填写了 minio的 地址和 用户名、密码

```
kind: Secret
apiVersion: v1
metadata:
  name: zjlab-backup-secret
  namespace: default
data:
  s3-endpoint: MTAuMTAxLjMyLjExOjkwMDA=   # 10.101.32.11:9000
  s3-access-key: YWRtaW4=         # admin
  s3-secret-key: cm9vdDEyMzQ1Ng== # root123456 
  s3-bucket: bXlzcWw=                         # mysql
type: Opaque
```

![image](https://user-images.githubusercontent.com/8857976/183824512-d38736e2-3f18-42a4-bfc6-05584d10ba96.png)
