### ISSUE TITLE
添加用户无法登录

### ISSUE THREAD

**Issue by aliuq** [radondb/radondb-mysql-kubernetes#653]
**Describe the problem**

按照官方示例安装 mysql_v1alpha1_mysqlcluster_mysql8.yaml，然后添加用户 mysql_v1alpha1_mysqluser.yaml

mysql_v1alpha1_mysqluser.yaml 删除了下面的配置
```yaml
withGrantOption: true
tlsOptions: 
  type: NONE
```

使用 super_user 和 RadonDB@123 无法登录，提示如下错误，猜测是密码错误
```bash
ERROR 1045 (28000): Access denied for user 'super_user'@'localhost' (using password: YES)
```

使用 radondb_usr 和 RadonDB@123 可以正常登录

- RadonDB MySQL version: 2.2.0
