### ISSUE TITLE
S3 备份失败

### ISSUE THREAD

**Issue by aliuq** [radondb/radondb-mysql-kubernetes#704]
**Describe the problem**

不知道哪个地方设置出现了问题

mysql_v1alpha1_mysqlcluster_mysql8

```yaml
apiVersion: mysql.radondb.com/v1alpha1
kind: MysqlCluster
metadata:
  name: sample
  namespace: radondb
spec:
  replicas: 3
  mysqlVersion: "8.0"
name:
  backupSecretName: backup-secret
…………
```

Secret

```yaml
kind: Secret
apiVersion: v1
metadata:
  name: backup-secret
  namespace: radondb
stringData:
  s3-endpoint: oss-cn-hangzhou.aliyuncs.com
  s3-access-key: xxxxxxxxxxxxxxx
  s3-secret-key: xxxxxxxxxxxxxxxxxxxxxxx
  s3-bucket: xx-mysql
type: Opaque
```

Backup

```yaml
apiVersion: mysql.radondb.com/v1alpha1
kind: Backup
metadata:
  name: backup-sample
  namespace: radondb
spec:
  # Add fields here
  image: radondb/mysql80-sidecar:v2.2.1
  hostName: sample-mysql-0
  clusterName: sample
```

打印日志

```bash
2022-09-21T03:03:43.410Z        INFO    sidecar initialize a backup     {"host": "sample-mysql-0.sample-mysql.radondb:8082", "endpoint": "/xbackup"}
2022-09-21T03:03:45.298Z        ERROR   sidecar run command failed      {"error": "fail to get backup: %!s(<nil>), code: 500 Internal Server Error"}
main.main.func3
        /workspace/cmd/sidecar/main.go:84
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main
        /workspace/cmd/sidecar/main.go:96
runtime.main
        /usr/local/go/src/runtime/proc.go:225
```

**Environment:**

- RadonDB MySQL version: `v2.2.1`
- Kubernetes version: `v1.23.9+k3s1`
- Helm version: `v3.9.4`
