### ISSUE TITLE
v2.2.1 升级 v2.3.0 init-sidecar 报错：invalid mysql version, currently we only support 5.7 or 8.0

### ISSUE THREAD

**Issue by jangrui** [radondb/radondb-mysql-kubernetes#761]
## sidecar 日志

```
panic: invalid mysql version, currently we only support 5.7 or 8.0

goroutine 1 [running]:
github.com/radondb/radondb-mysql-kubernetes/sidecar.NewInitConfig(0x15cb920)
	/workspace/sidecar/config.go:140 +0x10eb
main.main()
	/workspace/cmd/sidecar/main.go:91 +0x116
```

## MysqlCluster

```
apiVersion: mysql.radondb.com/v1alpha1
kind: MysqlCluster
metadata:
  name: openldap
spec:
  replicas: 3
  mysqlVersion: "5.7"
  mysqlOpts:
    mysqlConf:
      expire_logs_days: "7"
      innodb_buffer_pool_instances: "4"
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1
        memory: 2Gi

  metricsOpts:
    enabled: true

  podPolicy:
    slowLogTail: true
    auditLogTail: true

  persistence:
    enabled: true
    size: 10Gi
```

## Helm

```
helm upgrade -i radondb radondb/mysql-operator --version 2.3.0
```

> 升级后发现 mysqlclusters 中镜像还是 v2.2.1 的，手动替换后，错误依旧。
