### ISSUE TITLE
mysql user crds 创建的用户无法登陆，提示密码错误

### ISSUE THREAD

**Issue by jack-zhuhua** [radondb/radondb-mysql-kubernetes#772]
```
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-user-password
  namespace: mysql
data:
  adminUser: VnBVek8yMzZZbDYK

---
apiVersion: mysql.radondb.com/v1alpha1
kind: MysqlUser
metadata:
  name: admin-user
  namespace: mysql
spec:
  ## MySQL user name.
  user: admin
  withGrantOption: true
  tlsOptions:
    type: NONE
  hosts:
    - "%"
  permissions:
    - database: "*"
      tables:
        - "*"
      privileges:
        - ALL

  userOwner:
    clusterName: jmjs
    nameSpace: mysql

  secretSelector:
    secretName: mysql-user-password
    secretKey: adminUser
```

mysql -h $mysql_leader_ip  -uadmin -pVpUzO236Yl6 -P3306 
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'admin'@'172.22.2.54' (using password: YES)
