### ISSUE TITLE
3.0 无法使用nfs 备份

### ISSUE THREAD

**Issue by lostz** [radondb/radondb-mysql-kubernetes#827]
我安装文档设置nfsServerAddress 提示我错误信息为：strict decoding error: unknown field "spec.nfsServerAddress"
另外能否支持nfs 的path 路径添加

**Comment by acekingke** [comment]
3.0的alpha1的api 已经废弃，请使用beta1版本yaml
```
spec:
  backupops:
    nfs:
      volume: 
          nfs:
            server: xxxxxIP值
            path: /backup
  clusterName: sample
  method: xtrabackup
```
